### ISSUE TITLE
Modify require for cakephp3-bootstrap-helpers

### ISSUE THREAD

**Issue by Holt59** [cakemanager/cakeadmin-lightstrap#2]
The `cakephp3-bootstrap3-helpers` had its name and tagging system changed, so the require should now be:

```
"holt59/cakephp3-bootstrap-helpers": "~3.0"
```

Regards,
Mikael

**Comment by bobmulder** [comment]
Thank you @Holt59 for the service. I will leave this to @leoruhland.

**Comment by bobmulder** [comment]
@leoruhland Fixed in https://github.com/cakemanager/cakeadmin-lightstrap/commit/4fd22655e267c9b0693d53cf0896e6b049bc0a5c
